version: '3.9'

services:
  db:
    image: postgres:13
    container_name: postgres_library
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: library_management
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: 123456
      DATABASE_NAME: library_management
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  postgres_data:
